format_version: 4
pipelines:
  'prm-repo-pds-fhir-stub':
    group: performance
    label_template: '${git[:8]}'
    materials:
      git:
        type: configrepo
        ignore:
          - src/performance/**/*.*
    stages:
      - build:
          clean_workspace: true
          jobs:
            test_unit:
              resources:
                - docker
              artifacts:
                - build:
                    source: build
              tasks:
                - exec:
                    command: /bin/bash
                    arguments:
                      - -c
                      - ./tasks test_unit

      - docker:
          clean_workspace: true
          jobs:
            build:
              resources:
                - docker
              tasks:
                - fetch:
                    stage: build
                    job: test_unit
                    source: build
                - exec:
                    command: /bin/bash
                    arguments:
                      - -c
                      - ./tasks build_docker
